<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="Serilog.AspNetCore" />
    <PackageReference Include="Swashbuckle.AspNetCore" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\BuildingBlocks\Payments.BuildingBlocks.Infrastructure\Payments.BuildingBlocks.Infrastructure.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\Payments.BuildingBlocks.Observability\Payments.BuildingBlocks.Observability.csproj" />
    <ProjectReference Include="..\Payments.Identity.Application\Payments.Identity.Application.csproj" />
    <ProjectReference Include="..\Payments.Identity.Infrastructure\Payments.Identity.Infrastructure.csproj" />
  </ItemGroup>
</Project>