<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Confluent.Kafka" />
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="FluentAssertions" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\src\BuildingBlocks\Payments.BuildingBlocks.Domain\Payments.BuildingBlocks.Domain.csproj" />
    <ProjectReference Include="..\..\..\src\BuildingBlocks\Payments.BuildingBlocks.Application\Payments.BuildingBlocks.Application.csproj" />
    <ProjectReference Include="..\..\..\src\BuildingBlocks\Payments.BuildingBlocks.Messaging\Payments.BuildingBlocks.Messaging.csproj" />
    <ProjectReference Include="..\..\..\src\Services\Payments.Service.Template\Payments.Service.Template.Domain\Payments.Service.Template.Domain.csproj" />
    <ProjectReference Include="..\..\..\src\Services\Payments.Service.Template\Payments.Service.Template.Application\Payments.Service.Template.Application.csproj" />
  </ItemGroup>

</Project>